# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gaussian1 <- function(x) {
    .Call('monfuncreg_gaussian1', PACKAGE = 'monfuncreg', x)
}

estimate1 <- function(TT1, YYYY, NN, h1, weight, t) {
    .Call('monfuncreg_estimate1', PACKAGE = 'monfuncreg', TT1, YYYY, NN, h1, weight, t)
}

